
apiVersion: apps/v1
kind: Deployment
metadata:
  name: domcat-output
  namespace: domino-platform 
spec:
  selector:
    matchLabels:
      app: domcat-output
  template:
    metadata:
      labels:
        app: domcat-output
    spec:
      volumes:
        - name: output-data
          persistentVolumeClaim:
            claimName: domcat-output
      containers:
      - name: domcat-data-access
        image: quay.io/domino/python-public:3.9.6-slim
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;" ]
        volumeMounts:
          - mountPath: /output
            name: output-data
